### ISSUE TITLE
RemoveNodeTest is failing

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1116] opened 2017-12-27 19:52 UTC
## Overview

**Bug report.** It appears that merging in #1053 is causing removeNodeTest (possibly introduced by the PR) to fail on master.

**Comment by Maithem** [comment] 2017-12-27 22:34
This is caused by flakiness in the test "infrastructure", its not introduced by #1053.

**Comment by no2chem** [comment] 2017-12-27 22:37
Well, #1053 exercises the infrastructure in a way that consistently causes the bug to appear. We need to fix the test infrastructure before merging #1053. Otherwise CI will just keep breaking.

**Comment by Maithem** [comment] 2017-12-27 22:44
Looking at https://travis-ci.org/CorfuDB/CorfuDB/branches it doesn't seem to be consistent. 
Anyways, wrong epoch exceptions are expected in normal case. I added retry logic to make the test more robust https://github.com/CorfuDB/CorfuDB/pull/1118

I already spent some time investigating the test infra, will look at it again when I have time. Also, you might want to go ahead with your layoutThreadbranch.

**Comment by no2chem** [comment] 2017-12-27 22:56
Ok, not consistent, but its causing builds to fail pretty frequently.
Sure, I'll try to push layoutThread through. Let's run #1118 through a couple of times and push it through if its ok.

**Comment by Maithem** [comment] 2017-12-27 23:10
Are you seeing the failures locally ? out of the last 20 builds only two failed because of removeNode.
Also locally, I see it around 1 in 15 runs.

**Comment by no2chem** [comment] 2017-12-28 06:01
This seems to be still a problem after #1118 was remerged

See this build, for example: https://travis-ci.org/CorfuDB/CorfuDB/builds/322441795?utm_source=github_status&utm_medium=notification

**Comment by Maithem** [comment] 2017-12-28 06:29
#1118 fixes an the intermittently failing unit test (i.e. removeNode). This issue I have seen before and Its related having a failure just before the sequencer is reconfigured, which bricks the system since the sequencer is never configured again. I'm looking at it now.

**Comment by no2chem** [comment] 2017-12-28 07:38
Seems to be an actual failing test. Reproducible in 1/3-4 runs locally.

**Comment by Maithem** [comment] 2017-12-28 07:47
I'm debugging right now, I can see it 1 in 6 runs. I think its being caused by the attempt consensus code. If you look at the logs, a new layout is proposed, but an older one is returned after invalidate. 

 2017-12-27 23:04:11,381 INFO  [ServerRouter-0] o.c.i.BaseServer - handleMessageSetEpoch: Received SET_EPOCH, moving to new epoch 5
 2017-12-27 23:04:11,390 WARN  [ForkJoinPool.commonPool-worker-5] o.c.r.v.LayoutManagementView - Runtime recovered with a different layout = Layout(layoutServers=[localhost:9000, localhost:9001, localhost:9002],
 sequencers=[localhost:9000, localhost:9001, localhost:9002], segments=[Layout.LayoutSegment(replicationMode=CHAIN_REPLICATION, start=0, end=-1, stripes=[Layout.LayoutStripe(logServers=[localhost:9000, localhost
:9001, localhost:9002])])], unresponsiveServers=[], epoch=4)
 2017-12-27 23:04:11,391 ERROR [ForkJoinPool.commonPool-worker-5] o.c.p.w.o.Action - execute: error executing action
 org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=5]
        at org.corfudb.runtime.clients.BaseClient.handleWrongEpoch(BaseClient.java:165)

**Comment by Maithem** [comment] 2017-12-28 08:31
Ok, this problem seems to be caused by the interaction of attemptConsensus and invalidateLayout. When downsizing the cluster the clients invalidate code can read the layout from the removed node causing the epoch to regress and fail with WrongEpochException.

**Comment by no2chem** [comment] 2017-12-28 10:55
Ok, that doesn't quite explain why the test just hangs though? It seems to keep complaining the server is ready indefinitely....

**Comment by no2chem** [comment] 2017-12-28 11:18
I see the bug. ServerNotReadyException apparently doesn't invalidate the layout. I'll open a PR.

**Comment by no2chem** [comment] 2017-12-28 11:28
Ok, that wasn't the only issue...

**Comment by no2chem** [comment] 2017-12-28 11:54
I'm pretty sure the test is broken now. At least I understand this code path better.

It looks like sometimes workflows fail (with WrongEpochException). 
```
2017-12-28 03:27:58,222 INFO  [ForkJoinPool.commonPool-worker-3] o.c.i.o.Orchestrator - run: Started workflow REMOVE_NODE id 280af87f-4dc1-43ed-b8d6-8decb16dbd69
 2017-12-28 03:27:58,227 INFO  [ServerRouter-2] o.c.i.BaseServer - handleMessageSetEpoch: Received SET_EPOCH, moving to new epoch 5
 2017-12-28 03:27:58,228 INFO  [ServerRouter-1] o.c.i.BaseServer - handleMessageSetEpoch: Received SET_EPOCH, moving to new epoch 5
 2017-12-28 03:27:58,228 INFO  [ServerRouter-0] o.c.i.BaseServer - handleMessageSetEpoch: Received SET_EPOCH, moving to new epoch 5
 2017-12-28 03:27:58,236 WARN  [ForkJoinPool.commonPool-worker-3] o.c.r.v.LayoutManagementView - Runtime recovered with a different layout = Layout(layoutServers=[localhost:9000, localhost:9001, localhost:9002], sequencers=[localhost:9000, localhost:9001, localhost:9002], segments=[Layout.LayoutSegment(replicationMode=CHAIN_REPLICATION, start=0, end=-1, stripes=[Layout.LayoutStripe(logServers=[localhost:9000, localhost:9001, localhost:9002])])], unresponsiveServers=[], epoch=4)
 2017-12-28 03:27:58,238 ERROR [ForkJoinPool.commonPool-worker-3] o.c.p.w.o.Action - execute: error executing action
 org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=5]
	at org.corfudb.runtime.clients.BaseClient.handleWrongEpoch(BaseClient.java:165)
2017-12-28 03:27:58,238 INFO  [ForkJoinPool.commonPool-worker-3] o.c.i.o.Orchestrator - run: finished action RemoveNode for workflow 280af87f-4dc1-43ed-b8d6-8decb16dbd69 in 15 ms
 2017-12-28 03:27:58,238 ERROR [ForkJoinPool.commonPool-worker-3] o.c.i.o.Orchestrator - run: Failed to execute action RemoveNode for workflow 280af87f-4dc1-43ed-b8d6-8decb16dbd69, status ERROR, 
```
This causes the server to respond with
```
 2017-12-28 03:28:27,230 WARN  [ServerRouter-2] o.c.i.AbstractServer - Received message TOKEN_REQ but Server not ready.
```

I guess this is what you were saying @Maithem, but this seems to be really an issue with the way removeNode and the orchestrator works. Either the test needs to retry if the workflow fails (since it is the client's responsibility), or the removeNode needs to handle the case where one of its calls gets WrongEpochException. It could have been a NetworkException or other exception, for example, not necessarily WrongEpochException.

Either way, I think it points to an actual bug in #1118 and #1053, which could render a cluster unusable after reconfiguration. I'm going to move to revert #1118, and hopefully we can converge on a version of removeNode which works despite these failures.

**Closed** 2017-12-28 12:53 UTC
