### ISSUE TITLE
unit test failing on master

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#287] opened 2016-11-16 02:20 UTC
failedPolling is consistently failing on my machine

Results :

Failed tests: 
  PeriodicPollPolicyTest.failedPolling:128 expected:<{["test:9002"=false, "test:9001"=false]}> but was:<{[]}>

Tests run: 177, Failures: 1, Errors: 0, Skipped: 0

**Comment by Maithem** [comment] 2016-11-16 02:39
My machine is pretty slow, its passing on travis, but not locally, so I'm guessing this is a timing issue

**Comment by no2chem** [comment] 2016-11-16 19:05
It seems to be occasionally hanging in Travis as well...

**Comment by zalokhan** [comment] 2016-11-16 19:39
Yes this test should ideally take less than 5 seconds. But on my dev environment it takes 27 secs on average.
I'll investigate further to get the cause of this latency.

**Comment by zalokhan** [comment] 2016-11-16 22:09
The reason for this is not because of the test but its caused by the cleanup in AbstractViewTest after the test.
It tries to shutdown the ManagementServer which in turn tries to shutdown the CorfuRuntime it is using.
This shutdown takes a lot of time. (more than the time to run the test itself)

A quick and temporary fix for this test would be not to bootstrap the nodes and just test the polling of these running servers.
For the long term we need a method to quickly shutdown corfuRuntime instance.

**Comment by no2chem** [comment] 2016-11-16 22:42
Sure. I'll make sure the shutdown includes a timeout. Thanks.

**Comment by no2chem** [comment] 2016-11-16 22:46
Actually it seems the entire shutdown path in the CorfuRuntime needs cleanup. We'll add that to a new issue.

**Comment by no2chem** [comment] 2016-11-16 22:48
Upon even further inspection it looks like for some reason layout.get() is being called instead of layout.cancel()... switched to that instead of a timeout.

**Comment by zalokhan** [comment] 2016-11-16 22:53
If you are planning to use layout.cancel(), you will also have to monitor what exception you are thrown in the fetchLayout method. 
As we are currently catching all Exceptions, ignoring and continue polling. The interrupt or exception is hence lost.

**Comment by no2chem** [comment] 2016-11-16 23:04
If we're shutting down, I don't think there's a reason to catch the exceptions.

**Comment by no2chem** [comment] 2016-11-17 07:18
This is still intermittently failing. I think the reason is that the server does pingOnce asynchronously.

**Comment by Maithem** [comment] 2016-11-17 07:46
Should this be reverted and resolved, or should we continue to submit fixes?

**Comment by no2chem** [comment] 2016-11-17 07:47
I'm going to just convert pollOnce to async and be done with it rather than revert.

**Comment by no2chem** [comment] 2016-11-17 19:30
Ok maybe that wasn't the problem. @zalokhan, could you look further into this?

**Comment by zalokhan** [comment] 2016-11-17 20:22
Yes I am working on it but I cannot get the test to fail.
pollOnce already polls in async mode.

**Comment by zalokhan** [comment] 2016-11-18 21:39
This is resolved now.

**Closed by zalokhan** 2016-11-18 21:39 UTC
Labels: bug
