### ISSUE TITLE
Fetch latest layout using quorum

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#1560] opened 2018-11-15 22:57 UTC
## Overview

Currently in CorfuRuntime, the way of fetching the latest layout is to shuffle the layout servers, iterate through them until one layout server responds with the latest layout which has epoch larger than the current layout cache in CorfuRuntime. However this could cause issues that allow stale read/writes. The reason behind this is that when doing seal, we only wait for a quorum of layout servers to be sealed, then when fetching layout, we should also fetching a quorum instead of just one. 

## An example of this issue: 

Layout 0: s1, s2, s3 (all serve as layout servers and log unit servers, with s3 being sequencer).
Layout 1: s1, s2 (all serve as layout servers and log unit servers, with s1 being sequencer).

When sealing layout 0, assume only s1, s2 sealed successfully, and layout 1 is committed. Then an update-to-date client with layout 1 writes to the global tail.  After that a stale client with layout 0 cannot see this new global tail even after invalidate its layout since it's possible that this client is always fetching layout from s3 which doesn't have the latest layout.

## Proposed solution:

We could expose a new RPC from layout server for fetching paxos phase 2 data, and use those data to perform a quorum fetch of layout.

## Caution:

Some of the tests are relying on the current implementation of fetch layout, we need to modify these tests.

**Comment by zalokhan** [comment] 2019-04-19 23:03
Duplicate of #1443

**Closed by zalokhan** 2019-04-19 23:03 UTC
Labels: bug
