### ISSUE TITLE
Exception thrown by NettyClientRouter during message decoding

### ISSUE THREAD

**Issue by heidi-ann** [CorfuDB/CorfuDB#193] opened 2016-07-19 21:06 UTC
I am able to start a CorfuDB server, read and write to it, ping it and query layout. However, when adding another server to the layout, I get this message decoding error:

```
 13:24:11.666 ERROR [org.corfudb.runtime.clients.NettyClientRouter$2event-0] o.c.r.c.NettyClientRouter - Exception during channel handling.
 io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Attempt to deserialize a message which is not a CorfuMsg, Marker = 4 but expected 0xC0FC0FC0
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
Caused by: java.lang.RuntimeException: Attempt to deserialize a message which is not a CorfuMsg, Marker = 4 but expected 0xC0FC0FC0
    at org.corfudb.protocols.wireprotocol.CorfuMsg.deserialize(CorfuMsg.java:82)
13:24:11.667 TRACE [worker-0] o.c.r.c.NettyClientRouter - Disconnected, reconnecting...
 13:24:11.668 TRACE [main] o.c.r.c.NettyClientRouter - Disconnected endpoint localhost:8080
 13:24:11.668 DEBUG [org.corfudb.runtime.clients.NettyClientRouter$2event-1] o.c.r.c.NettyClientRouter - Registered new channel io.netty.channel.DefaultChannelHandlerContext@7b4ca27a
 13:24:11.668 ERROR [main] o.c.c.corfu_layouts - Exception
 org.corfudb.runtime.exceptions.NetworkException: Disconnected endpoint [endpoint=localhost:8080]
    at org.corfudb.runtime.clients.NettyClientRouter.sendMessageAndGetCompletable(NettyClientRouter.java:303)
RuntimeException exception: org.corfudb.runtime.exceptions.NetworkException: Disconnected endpoint [endpoint=localhost:8080]
```

Full trace is [here](https://github.com/CorfuDB/CorfuDB/files/372449/corfu_client_trace.txt).

To get this exception, I ran:

```
./corfu_server -ms 8080 -d TRACE
./corfu_server -m 8082 -d TRACE
./corfu_layouts add_layout -c localhost:8080 -e localhost:8082 -d TRACE
```

Some simple regression testing showed that this process work prior to https://github.com/CorfuDB/CorfuDB/commit/d824eed8c056f865ce9698efb83643e3aa3da630 However, this commit doesn't seem to edit the serialize/deserialize code.

[Here](https://github.com/CorfuDB/CorfuDB/files/372428/corfu_parsingerror_trace.pcap.txt) is a pcap trace of the packet exchange. It seems that all packets follow the expected structure below so I assume issue is with client side deserialization.
`length(4) | markerField(4) | client ID(16) | request ID(8) |  epoch(8)   |  type(1)  | payload`

My setup is as follows: 

```
$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.5", arch: "x86_64", family: "mac"
```

Can anyone advise?

Thanks

**Comment by no2chem** [comment] 2016-07-19 21:17
Thanks Heidi for taking a look and doing some debugging. Medhavi made this change, so I'll start by assigning the bug to him.

Meanwhile I'll take a look at the issue, it seems that the there was a change to LayoutMsg that isn't properly serializing/deserializing the buffers.

**Comment by medhavidhawan** [comment] 2016-07-19 23:06
Hi heidi, 
      thanks for reporting this. I am looking into this and will provide a fix soon. Yes this is a regression caused by my code. I will provide a fix soon.

**Comment by no2chem** [comment] 2016-07-22 17:12
Medhavi,

Is this closed by #197?

**Comment by medhavidhawan** [comment] 2016-07-22 17:40
@heidi-ann
     no this is not closed yet. I am going to upload the code in the next few hours for that.

**Comment by slfritchie** [comment] 2016-11-18 22:45
November review: Given all of the LayoutServer work, both server implementation & protocol changes, that this isn't a problem anymore, closing.

**Closed by slfritchie** 2016-11-18 22:45 UTC
