### ISSUE TITLE
Annoying Error Message

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#938] opened 2017-09-08 22:20 UTC
@zalokhan can you please look at this:

15:19:04,476 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:19:04,505 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[MetricsRollingFile] - Active log file name: /var/log/corfu-metrics.log
15:19:04,505 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[MetricsRollingFile] - File property is set to [/var/log/corfu-metrics.log]
15:19:04,506 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[MetricsRollingFile] - openFile(/var/log/corfu-metrics.log,true) call failed. java.io.FileNotFoundException: /var/log/corfu-metrics.log (Permission denied)
	at java.io.FileNotFoundException: /var/log/corfu-metrics.log (Permission denied)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
	at 	at org.corfudb.runtime.clients.BaseClient.<clinit>(BaseClient.java:28)
	at 	at java.lang.Class.forName0(Native Method)
	at 	at java.lang.Class.forName(Class.java:348)
	at 	at clojure.lang.RT.classForName(RT.java:2168)
	at 	at clojure.lang.RT.classForName(RT.java:2177)
	at 	at clojure.lang.Compiler.resolveIn(Compiler.java:7145)
	at 	at clojure.lang.Compiler.resolve(Compiler.java:7108)
	at 	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7069)
	at 	at clojure.lang.Compiler.analyze(Compiler.java:6648)
	at 	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at 	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1009)
	at 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at 	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at 	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at 	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at 	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at 	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
	at 	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
	at 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
	at 	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
	at 	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at 	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at 	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:589)
	at 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at 	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at 	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at 	at clojure.lang.Compiler.eval(Compiler.java:6931)
	at 	at clojure.lang.Compiler.load(Compiler.java:7379)
	at 	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at 	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at 	at clojure.lang.RT.load(RT.java:453)
	at 	at clojure.lang.RT.load(RT.java:419)
	at 	at clojure.core$load$fn__1621.invoke(core.clj:5893)
	at 	at clojure.core$load.invokeStatic(core.clj:5892)
	at 	at clojure.core$load.doInvoke(core.clj:5876)
	at 	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at 	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at 	at clojure.core$load_one.invoke(core.clj:5692)
	at 	at clojure.core$load_lib$fn__1570.invoke(core.clj:5737)
	at 	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at 	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at 	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at 	at clojure.core$apply.invokeStatic(core.clj:648)
	at 	at clojure.core$apply.invoke(core.clj:641)
	at 	at clojure.core$load_libs.invokeStatic(core.clj:5775)
	at 	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at 	at clojure.core$apply.invokeStatic(core.clj:648)
	at 	at clojure.core$apply.invoke(core.clj:641)
	at 	at clojure.core$require.invokeStatic(core.clj:5858)
	at 	at clojure.core$require.doInvoke(core.clj:5796)
	at 	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at 	at clojure.lang.Var.invoke(Var.java:379)
	at 	at org.corfudb.shell.ShellMain.main(ShellMain.java:13)
15:19:04,506 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qo

**Comment by zalokhan** [comment] 2017-09-09 00:13
Duplicate of #916

**Closed** 2017-09-09 00:21 UTC
